S1.

  Q1.    With 1 2 3 4 5 6 7 8 9, the program throws a NullPointerException, which in this case means the program
         is trying to access something which points to null instead of some sort of data. In this case,
         the error occurs at line 79.

  Q2.    Inputting 1 2 3 4 5 throws an ArrayIndexOutOfBounds exception, which means the program is trying
         to access unallocated memory. This error occurs at line 69.

  Q3.    Inputting 0-9 throws an Arithmetic exception. In this case, the exception is telling me
         that somewhere in the program is trying to divide by zero. This error occurs at line 60.

  Q4.    Inputting "hi" with the line of integers spits out a number format exception, which tells me that the
         program is expecting a string that can be parsed into integers. This error occurs at 52 and 65. Both
         sections of the program are trying to parse strings to int, and inputting "hi" makes the program throw a
         temper tantrum.

   Q5.   Running the program with the writeArrayToFile method uncommented spits out a requirement to throw a FileNotFoundException
         This error occurs at line 88.

S2. Completed.

S3. Completed.

S4. Completed.

S5. Completed.

S6. Well, I think the finally block might be useful if I wanted to determine whether the try block executed -- The finally block only
    only executes once the try block exits. I guess it could be used to easily hunt for bugs, but I haven't used them enough to see
    any use for them.
